---
abstract: 'Lazy way to produce test structures (Or a very bad idea)'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4206, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Fuckin-Lazy
provides:
  Fuckin::Lazy:
    file: lib/Fuckin/Lazy.pm
    version: '0.000002'
requires:
  Test::Simple: '0.88'
resources:
  bugtracker: http://github.com/exodist/Fuckin-Lazy/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Fuckin-Lazy
version: '0.000002'
